# Generated by Django 2.1.7 on 2019-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_info',
            field=models.CharField(choices=[('小学', '小学'), ('初中', '初中'), ('高中', '高中'), ('大学', '大学')], max_length=50, verbose_name='学校性质'),
        ),
    ]
