# Generated by Django 2.1.7 on 2019-05-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='答案'),
        ),
    ]
