# Generated by Django 2.1.7 on 2019-05-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0002_auto_20190428_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1234', max_length=30, verbose_name='密码'),
        ),
    ]
