# Generated by Django 2.1.7 on 2019-05-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0004_auto_20190518_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.CharField(default=0, max_length=50, verbose_name='录人员'),
        ),
    ]
