# Generated by Django 2.1.7 on 2019-05-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0005_auto_20190518_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
    ]
