# Generated by Django 2.1.7 on 2019-05-25 11:16

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0005_auto_20190525_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', DjangoUeditor.models.UEditorField(verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='题目内容'),
        ),
    ]
