# Generated by Django 2.1.7 on 2019-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0006_auto_20190518_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='user_id',
        ),
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.CharField(default=0, max_length=30, verbose_name='录人员'),
        ),
        migrations.AddField(
            model_name='paper_detail',
            name='point',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficult',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, max_length=30, verbose_name='难度系数'),
        ),
    ]
