# Generated by Django 2.1.7 on 2019-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0007_auto_20190518_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficult',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='难度系数'),
        ),
    ]
