# Generated by Django 2.1.7 on 2019-05-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_library', '0008_auto_20190518_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper_detail',
            old_name='paper_id',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='paper_detail',
            old_name='question_id',
            new_name='question',
        ),
    ]
